### ISSUE TITLE
为什么每次解密时要多读16个字节？

### ISSUE THREAD

**Issue by icsaas** [talver/SuperVideo#5]
为什么每次解密时要多读16个字节？

**Comment by talver** [comment]
密码长度是16个字节，加密后长度增加16，解密需要多读16个字节发自我的华为手机-------- 原始邮件 --------主题：[talver/SuperVideo] 为什么每次解密时要多读16个字节？ (#5)发件人："justpic.org" 收件人：talver/SuperVideo 抄送：Subscribed 

为什么每次解密时要多读16个字节？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/talver/SuperVideo/issues/5",

"url": "https://github.com/talver/SuperVideo/issues/5",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
